TITLE_BIOLOGICA_FRAME=BioLogica
HELP_GENO_PHENO=Geno-Pheno Help
HELP_MEIOSIS=Meiosis Help
HELP_PEDIGREE=Pedigree Help
HELP_MUTATIONS=Mutations Help
MENU_PRACTICE_SESSION=Practice Sessions
MENU_ITEM_GLOSSARY=Glossary
MENU_ITEM_PRACTICE_HELP=Practice Session Help
HELP_MENU_ITEM_CLOSE=Close
FILE_MENU_ITEM=File
FILE_MENU_ITEM_CLOSE=Close
FILE_MENU_ITEM_SET_SPECIES=Set Species
GENO_PHENO_SESSION=Geno-Pheno Practice Session
MENU_ITEM_MEIOSIS_PRACTICE_SESSION=Meiosis Practice Session
MENU_ITEM_PEDIGREE_PRACTICE_SESSION=Pedigree Practice Session
MENU_ITEM_MUTATE_PRACTICE_SESSION=Mutations Practice Session
MENU_PRACTICE_FILE=Practice File
MENU_ITEM_QUIT_PRACTICE_SESSION=Quit Practice Session
MENU_PRACTICE_HELP=Practice Help
TITLE_GENO_PHENO_PRACTICE_SESSION=Geno-Pheno Practice Session
TITLE_MEIOSIS_PRACTICE_SESSION=Meiosis Practice Session
TITLE_PEDIGREE_PRACTICE_SESSION=Pedigree Practice Session
TITLE_MUTATIONS_PRACTICE_SESSION=Mutations Practice Session
TITLE_HELP_FRAME=HELP
MENU_HELP_FILE=File
